job: extension
config:
  name: flux2
  process:
  - type: diffusion_trainer
    training_folder: /root/ai-toolkit/output
    sqlite_db_path: /root/ai-toolkit/aitk_db.db
    device: cuda
    trigger_word: null
    performance_log_every: 10
    network:
      type: lora
      linear: 32
      linear_alpha: 32
      conv: 16
      conv_alpha: 16
      lokr_full_rank: true
      lokr_factor: -1
      network_kwargs:
        ignore_if_contains: []
    save:
      dtype: bf16
      save_every: 250
      max_step_saves_to_keep: 4
      save_format: diffusers
      push_to_hub: false
    datasets:
    - folder_path: /root/ai-toolkit/datasets/flux2
      mask_path: null
      mask_min_value: 0.1
      default_caption: ''
      caption_ext: txt
      caption_dropout_rate: 0.05
      cache_latents_to_disk: false
      is_reg: false
      network_weight: 1
      resolution:
      - 512
      - 768
      - 1024
      controls: []
      shrink_video_to_frames: true
      num_frames: 1
      do_i2v: true
      flip_x: false
      flip_y: false
      control_path_1: null
      control_path_2: null
      control_path_3: null
    train:
      batch_size: 1
      bypass_guidance_embedding: false
      steps: 5000
      gradient_accumulation: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      timestep_type: weighted
      content_or_style: balanced
      optimizer_params:
        weight_decay: 0.0001
      unload_text_encoder: true
      cache_text_embeddings: false
      lr: 0.0001
      ema_config:
        use_ema: false
        ema_decay: 0.99
      skip_first_sample: false
      force_first_sample: false
      disable_sampling: false
      dtype: bf16
      diff_output_preservation: false
      diff_output_preservation_multiplier: 1
      diff_output_preservation_class: person
      switch_boundary_every: 1
      loss_type: mse
    model:
      name_or_path: "/.autodl/black-forest-labs/FLUX.2-dev" # 模型路径, 指向您本地缓存的模型文件夹
      quantize: true # [显存优化] 是否量化模型主体。True可以显著降低显存和提高速度，但可能轻微影响精度。
      qtype: qfloat8 # [显存优化] 量化类型, qfloat8是一种积极的量化方式。
      quantize_te: true # [显存优化] 是否量化文本编码器(TE)。对于大型文本编码器(如Mistral), 强烈建议开启。
      qtype_te: qfloat8 # [显存优化] 文本编码器的量化类型。
      arch: flux2
      low_vram: true # [显存优化] 是否开启低显存模式。会把不用的模型组件卸载到CPU, 以节省显存。
      model_kwargs:
        match_target_res: true
      layer_offloading: false # [显存优化] 更精细的层卸载控制, low_vram开启时通常不用额外设置。
      layer_offloading_text_encoder_percent: 1
      layer_offloading_transformer_percent: 1
    # === 预览图生成 (已禁用) ===
    # 为了节省大约10GB显存, 以下sample部分已被注释掉。
    # 如果需要重新开启, 请取消注释并确保有足够显存。
    # sample:
    #   sampler: flowmatch
    #   sample_every: 250 # 每训练250步生成一次预览图
    #   width: 1024
    #   height: 1024
    #   samples:
    #   - prompt: xingstyle, teddy bear, crystal sculpture, geometric design, red color,
    #       reflective surface, polygonal structure, glossy finish, decorative art,
    #       bow tie, faceted texture, transparent appearance, modern artwork, shiny,
    #       collectible item, ornamental figurine, abstract teddy bear, 3D rendering,
    #       creative design.
    #   - prompt: xingstyle, 3d,1dog
    #   - prompt: xingstyle, 3d,1cat
    #   neg: ''
    #   seed: 42
    #   walk_seed: true
    #   guidance_scale: 4
    #   sample_steps: 25
    #   num_frames: 1
    #   fps: 1
meta:
  name: flux2
  version: '1.0'
